#!/usr/bin/env python3
import IPython
import numpy as np
import matplotlib.pylab as plt
import h5py
from IPython.frontend.terminal.embed import InteractiveShellEmbed
from traitlets.config.loader import Config
import click
from pathlib import Path
from typing import List


@click.command()
@click.argument("files", nargs=-1)
@click.option("--amode", "-a", is_flag=True, default=False)
def cli(files, amode):
    mode = "a" if amode else "r"
    scripts = []

    def process_file(h5files:List, f: Path, mode):
        if f.suffix == ".h5":
            h5files.append(h5py.File(i, mode))
        else:
            scripts.append(f.absolute())

    f = []
    for i in files:
        process_file(f, Path(i), mode)
    if len(f) == 1:
        f = f[0]
    for s in scripts:
        with s.open() as fp:
            exec(fp.read())

    c = Config()
    c.TerminalInteractiveShell.banner2 = "try: print(f)"
    shell = InteractiveShellEmbed(config=c)
    shell.magic("matplotlib")
    shell()
    if "f" in locals():
        if isinstance(f, list):
            for i in f:
                i.close()
        elif isinstance(f, h5py.File):
            f.close()


if __name__ == "__main__":
    cli()
