#!/usr/bin/env python3
import click


@click.command()
@click.argument("files", nargs=-1)
@click.option("--amode", "-a", help="The append mode", is_flag=True, default=False)
def cli(files, amode):
    import h5py

    mode = "a" if amode else "r"
    if len(files) == 1:
        f = h5py.File(files[0], mode)
    else:
        f = [h5py.File(i, mode) for i in files]

    import IPython
    import numpy as np
    import matplotlib.pylab as plt
    from IPython.terminal.embed import InteractiveShellEmbed
    from traitlets.config.loader import Config

    c = Config()
    c.TerminalInteractiveShell.banner2 = "Try: print(f)"
    shell = InteractiveShellEmbed(config=c)
    shell.magic("matplotlib")
    shell()
    if "f" in locals():
        if isinstance(f, list):
            for i in f:
                i.close()
        elif isinstance(f, h5py.File):
            f.close()


if __name__ == "__main__":
    cli()
