#!/usr/bin/env python3
import click
from pathlib import Path
from typing import List
import h5py

__doc__ = """This command reads hdf5 files then puts them in a list `f`."""


def process_file(files, mode):
    h5files = []
    scripts = []
    for i in map(Path, files):
        if i.suffix == ".h5":
            h5files.append(h5py.File(i, mode))
        else:
            scripts.append(i.absolute())
    return h5files, scripts

@click.command(help=__doc__)
@click.argument("files", nargs=-1)
@click.option("--mode", "-m", help="The append mode", default="r")
def cli(files, mode):
    f, scripts = process_file(files, mode)
    if len(f) == 1:
        f = f[0]
    for s in scripts:
        with s.open() as fp:
            exec(fp.read(), globals())

    import IPython
    import numpy as np
    import matplotlib.pylab as plt
    from IPython.terminal.embed import InteractiveShellEmbed
    from traitlets.config.loader import Config

    c = Config()
    c.TerminalInteractiveShell.banner2 = "Try: print(f)"
    shell = InteractiveShellEmbed(config=c)
    shell.magic("matplotlib")
    shell()
    if "f" in locals():
        if isinstance(f, list):
            for i in f:
                i.close()
        elif isinstance(f, h5py.File):
            f.close()


if __name__ == "__main__":
    cli()
